# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfbcf34611cbec0166ad6bf6ba4c701c22b95b545a460882f6eed7dfa0e52b01f7e459c112c0ea970b468bad47867c68218b818ad4dd61deedb6d39715f669ee

test:
  secret_key_base: 4567f10dc35e2a9907763476ff0041d071eca17011e71dea46fa9e9623c21b131de5c8dfe9638a04bbf4e15f0021df838ffb28d28a2d63fc0b718ef2e30bb56b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
